root: true
env:
  browser: true
  node: true
  es6: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  # When Use TypeScript, Setting of Root Dir. ( To Find for tsconfig.json )
  tsconfigRootDir: '.'
  # When Use TypeScript, Import tsconfig Setting.
  project: './tsconfig.json'
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - import
  - jest
  - react
  - react-hooks
  - testing-library
  - jsx-a11y
  - jest-dom
  - simple-import-sort
settings:
  # Import webpack Alias Setting, Linting for 'import/no-unresolved'.
  'import/resolver':
    webpack:
      config: 'webpack/webpack.base.babel.js'
  react:
    version: 'detect'
  node:
    tryExtensions:
      - '.js'
      - '.ts'
      - '.jsx'
      - '.tsx'
      - '.json'
      - '.node'
#
#
# Set Linting Rules Below.
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:testing-library/react'
  - 'plugin:jest-dom/recommended'
  - 'prettier'
rules:
  indent: off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/prefer-interface': off
  '@typescript-eslint/explicit-function-return-type': warn
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: '^AddIgnoreName'
  '@typescript-eslint/no-implicit-any-catch':
    - error
    - allowExplicitAny: true
  'max-classes-per-file':
    - error
    - 2
  'no-bitwise':
    - error
    - allow:
        - '~'
  'jsx-a11y/alt-text':
    - warn
    - elements:
        - 'img'
      img:
        - 'Image'
  'import/no-anonymous-default-export': warn
  'import/order': off
  'sort-keys': off
  'no-multiple-empty-lines': off
  'lines-between-class-members':
    - error
    - always
    - exceptAfterSingleLine: true
  'no-console': off
  'unicorn/number-literal-case': off
  'spaced-comment':
    - error
    - always
  'react/prop-types': off
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': warn
  'react/jsx-uses-react': off
  'react/react-in-jsx-scope': off
  'simple-import-sort/imports': error
  'simple-import-sort/exports': error
  '@typescript-eslint/ban-ts-comment': off
