name: CI for Preview
on:
  pull_request:
    types: synchronize
    branches: master

env:
  LAUNCH_ESLINT: on # Launch ESLint. [ on, off ]
  LAUNCH_STYLELINT: on # Launch stylelint. [ on, off ]
  LAUNCH_BUILD: on # Launch Build. [ on, off ]

jobs:
  eslint-and-stylelint:
    name: ESLint & stylelint for Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execution Environment for Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set Env
        run: |
          echo "LAUNCH_ESLINT=${LAUNCH_ESLINT}" >> $GITHUB_ENV
          echo "LAUNCH_STYLELINT=${LAUNCH_STYLELINT}" >> $GITHUB_ENV
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: yarn
      - name: Do ESLint
        if: env.LAUNCH_ESLINT == 'on'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'resource/**/*.{ts,tsx,js,jsx}'
      - name: Displayed ESLINT Failure on Checks
        if: env.LAUNCH_ESLINT == 'on'
        run: yarn eslint 'resource/**/*.{ts,tsx,js,jsx}' --max-warnings 0
      - name: Do stylelint
        if: env.LAUNCH_STYLELINT == 'on'
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: 'resource/**/*.{ts,tsx,js,jsx}'
      - name: Displayed stylelint Failure on Checks
        if: env.LAUNCH_STYLELINT == 'on'
        run: yarn stylelint 'resource/**/*.{ts,tsx,js,jsx}'

  build-test:
    name: Build Test for Preview
    needs: eslint-and-stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execution Environment for Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set Env
        run: echo "LAUNCH_BUILD=${LAUNCH_BUILD}" >> $GITHUB_ENV
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: yarn
      - name: Do Build Test
        if: env.LAUNCH_BUILD == 'on'
        run: yarn build