name: Preview
on:
  pull_request:
    types: closed
    branches: main

env:
  NODE_VERSION: 16.x
  LAUNCH_BUILD: on # Launch Build. [ on, off ]
  LAUNCH_DEPLOY: on # Launch Deployment. [ on, off ]
  ENDPOINT_GITHUB_PAGES: https://kojiyamauchi.github.io/react-simple-starter # When Using GitHub Pages, Add Endpoint.
  ENDPOINT_REDIRECT: https://kojiyamauchi.github.io/react-simple-starter # When Create SPA & Deploy on GitHub Pages, Add GitHub Pages Endpoint.

jobs:
  preview:
    name: Build & Deploy for Preview
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execution Environment for Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node Modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-
      - name: Install Dependencies
        run: yarn
      - name: Do Build
        if: env.LAUNCH_BUILD == 'on'
        run: yarn build
      - name: Clean Delivery Directory
        if: env.LAUNCH_DEPLOY == 'on'
        run: rm delivery/.gitkeep
      - name: Do Deploy
        if: env.LAUNCH_DEPLOY == 'on'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: preview
          publish_dir: ./delivery

  report:
    name: Done's Report for Preview
    needs: preview
    runs-on: ubuntu-latest
    steps:
      - name: Finished GitHub Pages Deploy
        if: env.LAUNCH_DEPLOY == 'on' && env.ENDPOINT_GITHUB_PAGES != null
        run: echo ${{ env.ENDPOINT_GITHUB_PAGES }}
